[technote]
id = "SQR-076"
series_id = "SQR"
canonical_url = "https://sqr-076.lsst.io"
github_url = "https://github.com/lsst-sqre/sqr-076"
github_default_branch = "main"
# version = "1.0.0"
date_created = "2023-04-20"
# date_updated = "2023-04-20"

[[technote.authors]]
name = { given_names = "Jonathan", family_names = "Sick" }
orcid = "https://orcid.org/0000-0003-3001-676X"
affiliations = [
    { name = "Rubin Observatory", ror = "https://ror.org/048g3cy84" },
]

[sphinx.intersphinx]
projects = { "kafkit" = "https://kafkit.lsst.io/" }
